-- 01_drop.sql
DROP VIEW IF EXISTS match_results_with_pk;

DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS MatchParticipant;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Match;
DROP TABLE IF EXISTS Coach;
DROP TABLE IF EXISTS NationalTeam;
DROP TABLE IF EXISTS Venue;
