-- 04_seed_facts.sql
-- Fact data: Player, Match, MatchParticipant, Goal
-- (Assumes Schema B: Goal has is_penalty_shootout BOOLEAN)

-- =========================================================
-- Insert Players  （←ここは君の Player INSERT を “そのまま全部” コピペ）
-- =========================================================
INSERT INTO Player (lastname, surname, position, height, nationality) VALUES
('Timber','Jurrien','Defender',1.82,'Netherlands'),
('Ndiaye','Iliman','Midfielder',1.8,'Senegal'),
('Grbic','Ivo','Goalkeeper',1.95,'Croatia'),
('Ryan','Mathew','Goalkeeper',1.84,'Australia'),
('Otamendi','Nicolás','Defender',1.83,'Argentina'),
('Patrício','Rui','Goalkeeper',1.9,'Portugal'),
('Schmeichel','Kasper','Goalkeeper',1.89,'Denmark'),
('Hwang','Ui-jo','Forward',1.85,'South Korea'),
('Yedlin','DeAndre','Defender',1.73,'USA'),
('Shaqiri','Xherdan','Midfielder',1.69,'Switzerland'),
('Aguilera','Brandon','Midfielder',1.79,'Costa Rica'),
('Grosicki','Kamil','Midfielder',1.8,'Poland'),
('Odoi','Denis','Defender',1.78,'Ghana'),
('Orsic','Mislav','Forward',1.79,'Croatia'),
('Rodon','Joe','Defender',1.93,'Wales'),
('N"Koulou','Nicolas','Defender',1.84,'Cameroon'),
('Ampadu','Ethan','Defender',1.83,'Wales'),
('Alderweireld','Toby','Defender',1.87,'Belgium'),
('García','Eric','Defender',1.82,'Spain'),
('Saïss','Romain','Defender',1.88,'Morocco'),
('Rüdiger','Antonio','Defender',1.9,'Germany'),
('Telles','Alex','Defender',1.81,'Brazil'),
('Zaroury','Anass','Forward',1.76,'Morocco'),
('Giroud','Olivier','Forward',1.92,'France'),
('Christensen','Andreas','Defender',1.87,'Denmark'),
('Machado Ferrira','Vitor','Midfielder',1.72,'Portugal'),
('Souttar','Harry','Defender',1.98,'Australia'),
('Vina','Matias','Defender',1.8,'Uruguay'),
('Ballo-Toure','Fode','Defender',1.82,'Senegal'),
('Gvardiol','Josko','Defender',1.85,'Croatia'),
('Disasi','Axel','Defender',1.9,'France'),
('Batshuayi','Michy','Forward',1.85,'Belgium'),
('Xhaka','Granit','Midfielder',1.86,'Switzerland'),
('Hennessey','Wayne','Goalkeeper',1.98,'Wales'),
('Roberts','Connor','Defender',1.75,'Wales'),
('Horvath','Ethan','Goalkeeper',1.95,'USA'),
('Endo','Wataru','Midfielder',1.78,'Japan'),
('Lockyer','Tom','Defender',1.85,'Wales'),
('Torres','Pau','Defender',1.91,'Spain'),
('Martínez','Emiliano','Goalkeeper',1.95,'Argentina'),
('Kudus','Mohammed','Midfielder',1.77,'Ghana'),
('Kouyaté','Cheikhou','Defender',1.89,'Senegal'),
('Vlasic','Nikola','Midfielder',1.78,'Croatia'),
('Dias','Ruben','Defender',1.87,'Portugal'),
('Navas','Keylor','Goalkeeper',1.85,'Costa Rica'),
('Faes','Wout','Defender',1.87,'Belgium'),
('Felix','Joao','Forward',1.81,'Portugal'),
('Nunez','Darwin','Forward',1.87,'Uruguay'),
('Aaronson','Brenden','Midfielder',1.77,'USA'),
('Dalot','Diogo','Defender',1.83,'Portugal'),
('Fati','Ansu','Forward',1.78,'Spain'),
('Tomiyasu','Takehiro','Defender',1.88,'Japan'),
('Kiwior','Jakub','Midfielder',1.89,'Poland'),
('Silva','Bernardo','Midfielder',1.73,'Portugal'),
('Cancelo','João','Defender',1.82,'Portugal'),
('Alvarez','Julian','Forward',1.7,'Argentina'),
('Adams','Tyler','Midfielder',1.75,'USA'),
('Laporte','Aymeric','Defender',1.89,'Spain'),
('Kristensen','Rasmus','Defender',1.87,'Denmark'),
('Gündogan','Ilkay','Midfielder',1.8,'Germany'),
('Davies','Ben','Defender',1.81,'Wales'),
('Mepham','Chris','Defender',1.9,'Wales'),
('Salisu','Mohammed','Defender',1.88,'Ghana'),
('Sarabia','Pablo','Forward',1.74,'Spain'),
('Dier','Eric','Defender',1.88,'England'),
('Perisic','Ivan','Midfielder',1.86,'Croatia'),
('Ronaldo','Cristiano','Forward',1.87,'Portugal'),
('Cash','Matthew','Defender',1.85,'Poland'),
('Paquetá','Lucas','Forward',1.8,'Brazil'),
('Guimaraes','Bruno','Midfielder',1.82,'Brazil'),
('Pellistri','Facundo','Forward',1.74,'Uruguay'),
('Romero','Cristian','Defender',1.85,'Argentina'),
('Onana','Amadou','Midfielder',1.95,'Belgium'),
('Pope','Nick','Goalkeeper',1.98,'England'),
('Rice','Declan','Midfielder',1.88,'England'),
('Andersen','Joachim','Defender',1.92,'Denmark'),
('Alvarez','Edson','Midfielder',1.87,'Mexico'),
('Fernandez','Enzo','Midfielder',1.78,'Argentina'),
('Schär','Fabian','Defender',1.86,'Switzerland'),
('Turner','Matt','Goalkeeper',1.91,'USA'),
('Palhinha','Joao','Midfielder',1.9,'Portugal'),
('Sá','José','Goalkeeper',1.92,'Portugal'),
('Zambo','André Zambo','Midfielder',1.84,'Cameroon'),
('Lukaku','Romelu','Forward',1.91,'Belgium'),
('Grealish','Jack','Midfielder',1.8,'England'),
('Onana','Andre','Goalkeeper',1.9,'Cameroon'),
('Castagne','Timothy','Defender',1.85,'Belgium'),
('Shaw','Luke','Defender',1.78,'England'),
('Aké','Nathan','Defender',1.8,'Netherlands'),
('Koulibaly','Kalidou','Defender',1.86,'Senegal'),
('Ream','Tim','Defender',1.86,'USA'),
('Alexander-Arnold','Trent','Defender',1.8,'England'),
('Rodrigues de Paula Santos','Frederico','Midfielder',1.69,'Brazil'),
('Casemiro','Carlos','Midfielder',1.85,'Brazil'),
('Henderson','Jordan','Midfielder',1.87,'England'),
('McKennie','Weston','Midfielder',1.85,'USA'),
('Trippier','Kieran','Defender',1.73,'England'),
('Sánchez','Robert','Goalkeeper',1.97,'Spain'),
('Martinez','Lisandro','Defender',1.75,'Argentina'),
('Estupinan','Pervis','Defender',1.75,'Ecuador'),
('Son','Heung-min','Forward',1.84,'South Korea'),
('Pickford','Jordan','Goalkeeper',1.85,'England'),
('Bentancur','Rodrigo','Midfielder',1.87,'Uruguay'),
('Robinson','Antonee','Defender',1.83,'USA'),
('Azpilicueta','César','Defender',1.78,'Spain'),
('Santana de Moraes','Ederson','Goalkeeper',1.88,'Brazil'),
('Ramses Becker','Alisson','Goalkeeper',1.93,'Brazil'),
('Bednarek','Jan','Defender',1.89,'Poland'),
('Henrique Tavares','Fabio','Midfielder',1.88,'Brazil'),
('Ghoddos','Saman','Forward',1.75,'Iran'),
('Saliba','William','Defender',1.92,'France'),
('Lloris','Hugo','Goalkeeper',1.88,'France'),
('Malacia','Tyrell','Defender',1.69,'Netherlands'),
('Mendy','Nampalys','Midfielder',1.67,'Senegal'),
('Stones','John','Defender',1.88,'England'),
('Nunes','Matheus','Midfielder',1.83,'Portugal'),
('Nörgaard','Christian','Midfielder',1.87,'Denmark'),
('Gueye','Idrissa','Midfielder',1.74,'Senegal'),
('Aguerd','Nayef','Defender',1.9,'Morocco'),
('Gakpo','Cody','Forward',1.93,'Netherlands'),
('De Bruyne','Kevin','Midfielder',1.81,'Belgium'),
('White','Ben','Defender',1.86,'England'),
('van Dijk','Virgil','Defender',1.93,'Netherlands'),
('Bella-Kotchap','Armel','Defender',1.9,'Germany'),
('Jensen','Mathias','Midfielder',1.8,'Denmark'),
('Walker','Kyle','Defender',1.83,'England'),
('Raya','David','Goalkeeper',1.83,'Spain'),
('Ayew','Andre','Forward',1.75,'Ghana'),
('Areola','Alphonse','Goalkeeper',1.95,'France'),
('Silva','Thiago','Defender',1.81,'Brazil'),
('Phillips','Kalvin','Midfielder',1.79,'England'),
('Sarr','Pape','Midfielder',1.84,'Senegal'),
('Mendy','Edouard','Goalkeeper',1.94,'Senegal'),
('Coady','Conor','Defender',1.85,'England'),
('Ward','Danny','Goalkeeper',1.91,'Wales'),
('Partey','Thomas','Midfielder',1.85,'Ghana'),
('Matheus dos Santos','Antony','Forward',1.72,'Brazil'),
('Mitoma','Kaoru','Forward',1.78,'Japan'),
('Mitrovic','Aleksandar','Forward',1.89,'Serbia'),
('Sulemana','Kamaldeen','Forward',1.75,'Ghana'),
('Akanji','Manuel','Defender',1.88,'Switzerland'),
('Amartey','Daniel','Defender',1.86,'Ghana'),
('Neves','Rúben','Midfielder',1.8,'Portugal'),
('Hernández Cascante','Rodrigo','Midfielder',1.91,'Spain'),
('Minamino','Takumi','Forward',1.72,'Japan'),
('Cavani','Edinson','Forward',1.84,'Uruguay'),
('Tielemans','Youri','Midfielder',1.76,'Belgium'),
('Freuler','Remo','Midfielder',1.8,'Switzerland'),
('Semenyo','Antoine','Forward',1.85,'Ghana'),
('Wilson','Harry','Forward',1.73,'Wales'),
('Höjbjerg','Pierre-Emile','Midfielder',1.85,'Denmark'),
('Doku','Jeremy','Forward',1.73,'Belgium'),
('Konaté','Ibrahima','Defender',1.94,'France'),
('Montiel','Gonzalo','Defender',1.75,'Argentina'),
('Davies','Adam','Goalkeeper',1.85,'Wales'),
('Varane','Raphael','Defender',1.91,'France'),
('Johnson','Brennan','Midfielder',1.79,'Wales'),
('Amrabat','Sofyan','Midfielder',1.85,'Morocco'),
('Caicedo','Moises','Midfielder',1.78,'Ecuador'),
('Maguire','Harry','Defender',1.94,'England'),
('Ramsdale','Aaron','Goalkeeper',1.9,'England'),
('Williams','Neco','Defender',1.83,'Wales'),
('Mejbri','Hannibal','Midfielder',1.77,'Tunisia'),
('Jackson','Nicolas','Forward',1.88,'Senegal'),
('Lukić','Saša','Midfielder',1.83,'Serbia'),
('Slimane','Anis','Midfielder',1.88,'Tunisia'),
('Moore','Kieffer','Forward',1.96,'Wales'),
('Kehrer','Thilo','Defender',1.86,'Germany'),
('Kovacic','Mateo','Midfielder',1.77,'Croatia'),
('Rashford','Marcus','Forward',1.85,'England'),
('Bale','Gareth','Forward',1.86,'Wales'),
('Torres Garcia','Ferran','Forward',1.82,'Spain'),
('Gallagher','Conor','Midfielder',1.82,'England'),
('Bergwijn','Steven','Forward',1.78,'Netherlands'),
('Jahanbakhsh','Alireza','Forward',1.81,'Iran'),
('Pulisic','Christian','Forward',1.77,'USA'),
('Eriksen','Christian','Midfielder',1.82,'Denmark'),
('Zakaria','Denis','Midfielder',1.9,'Switzerland'),
('MacAllister','Alexis','Forward',1.74,'Argentina'),
('Dendoncker','Leander','Midfielder',1.88,'Belgium'),
('Foden','Phil','Midfielder',1.71,'England'),
('Ziyech','Hakim','Forward',1.81,'Morocco'),
('Kane','Harry','Forward',1.88,'England'),
('Hwang','Hee-chan','Forward',1.77,'South Korea'),
('Fernandes','Bruno','Midfielder',1.79,'Portugal'),
('Lamptey','Tariq','Defender',1.63,'Ghana'),
('Weghorst','Wout','Forward',1.97,'Netherlands'),
('James','Daniel','Forward',1.71,'Wales'),
('Havertz','Kai','Midfielder',1.93,'Germany'),
('Sarmiento','Jeremy','Forward',1.78,'Ecuador'),
('Maddison','James','Midfielder',1.75,'England'),
('Mount','Mason','Midfielder',1.81,'England'),
('Mbeumo','Bryan','Forward',1.71,'Cameroon'),
('Jiménez','Raúl','Forward',1.88,'Mexico'),
('Ayew','Jordan','Forward',1.82,'Ghana'),
('Saka','Bukayo','Midfielder',1.78,'England'),
('de Andrade','Richarlison','Forward',1.84,'Brazil'),
('Martinelli','Gabriel','Forward',1.78,'Brazil'),
('Sarr','Ismaïla','Forward',1.85,'Senegal'),
('Sterling','Raheem','Forward',1.7,'England'),
('Damsgaard','Mikkel','Forward',1.8,'Denmark'),
('Trossard','Leandro','Forward',1.72,'Belgium'),
('Dias Belloli','Raphael','Midfielder',1.76,'Brazil'),
('Wilson','Callum','Forward',1.8,'England'),
('Jesus','Gabriel','Forward',1.75,'Brazil'),
('Sargent','Josh','Forward',1.85,'USA'),
('Schmidt','Daniel','Goalkeeper',1.97,'Japan'),
('Yoshida','Maya','Defender',1.89,'Japan'),
('Sakai','Hiroki','Defender',1.85,'Japan'),
('Shibasaki','Gaku','Midfielder',1.74,'Japan'),
('Ito','Junya','Midfielder',1.76,'Japan'),
('Kamada','Daichi','Midfielder',1.84,'Japan'),
('Asano','Takuma','Forward',1.73,'Japan'),
('Kubo','Takefusa','Forward',1.73,'Japan'),
('Araujo','Nestor','Defender',1.88,'Mexico'),
('Busquets','Sergio','Midfielder',1.89,'Spain'),
('Romo','Luis','Midfielder',1.84,'Mexico'),
('Asensio','Marco','Forward',1.82,'Spain'),
('Morata','Alvaro','Forward',1.89,'Spain'),
('Weah','Timothy','Forward',1.83,'USA'),
('Lozano','Hirving','Forward',1.75,'Mexico'),
('Antuna','Uriel','Forward',1.74,'Mexico'),
('Moore','Shaquell','Defender',1.8,'USA'),
('Acosta','Kellyn','Midfielder',1.77,'USA'),
('Alvarado','Roberto','Forward',1.76,'Mexico'),
('Cornelius','Derek','Defender',1.88,'Canada'),
('Calvo','Francisco','Defender',1.8,'Costa Rica'),
('Adekugbe','Sam','Defender',1.76,'Canada'),
('Mbaizo','Olivier','Defender',1.78,'Cameroon'),
('Hoilett','Junior','Forward',1.74,'Canada'),
('Méndez','Jhegson','Midfielder',1.7,'Ecuador'),
('Messi','Lionel','Forward',1.7,'Argentina'),
('Piette','Samuel','Midfielder',1.71,'Canada'),
('Oviedo','Bryan','Defender',1.72,'Costa Rica'),
('Osorio','Jonathan','Midfielder',1.75,'Canada'),
('Buchanan','Tajon','Forward',1.83,'Canada'),
('Estrada','Michael','Forward',1.87,'Ecuador'),
('Kone','Ismael','Midfielder',1.88,'Canada'),
('Degenek','Milos','Defender',1.87,'Australia'),
('Ferreira','Jesús','Forward',1.75,'USA'),
('Palacios','Diego','Defender',1.69,'Ecuador'),
('Cáceres','Martín','Defender',1.8,'Uruguay'),
('Kaye','Mark-Anthony','Midfielder',1.85,'Canada'),
('Cifuentes','José','Midfielder',1.78,'Ecuador'),
('St Clair','Dayne','Goalkeeper',1.91,'Canada'),
('Alba','Jordi','Defender',1.7,'Spain'),
('Fraser','Liam','Midfielder',1.85,'Canada'),
('Almada','Thiago','Midfielder',1.71,'Argentina'),
('Long','Aaron','Defender',1.86,'USA'),
('Laryea','Richie','Defender',1.75,'Canada'),
('Cavallini','Lucas','Forward',1.82,'Canada'),
('Frankowski','Przemyslaw','Forward',1.75,'Poland'),
('Johnson','Sean','Goalkeeper',1.9,'USA'),
('Johnston','Alistair','Defender',1.8,'Canada'),
('Gruezo','Carlos','Midfielder',1.72,'Ecuador'),
('Herrera','Hector','Midfielder',1.8,'Mexico'),
('Swiderski','Karol','Forward',1.84,'Poland'),
('Pantemis','James','Goalkeeper',1.91,'Canada'),
('Morris','Jordan','Forward',1.81,'USA'),
('Roldán','Cristian','Midfielder',1.73,'USA'),
('Miller','Kamal','Defender',1.83,'Canada'),
('Franco','Alan','Midfielder',1.75,'Ecuador'),
('Torres','Facundo','Forward',1.77,'Uruguay'),
('Kim','Moon-hwan','Defender',1.73,'South Korea'),
('Tolo','Nouhou','Defender',1.78,'Cameroon'),
('Zimmerman','Walker','Defender',1.9,'USA'),
('Waterman','Joel','Defender',1.88,'Canada'),
('Matarrita','Ronald','Defender',1.75,'Costa Rica'),
('Arreaga','Xavier','Defender',1.84,'Ecuador'),
('Radonjic','Nemanja','Forward',1.85,'Serbia'),
('Rajkovic','Predrag','Goalkeeper',1.92,'Serbia'),
('Omlin','Jonas','Goalkeeper',1.9,'Switzerland'),
('Camavinga','Eduardo','Midfielder',1.82,'France'),
('Simons','Xavi','Midfielder',1.79,'Netherlands'),
('Pavlovic','Strahinja','Defender',1.94,'Serbia'),
('Lee','Kang-in','Midfielder',1.73,'South Korea'),
('Mendes','Nuno','Defender',1.83,'Portugal'),
('Ebosse','Enzo','Defender',1.85,'Cameroon'),
('Bronn','Dylan','Defender',1.86,'Tunisia'),
('Diallo','Abdou','Defender',1.87,'Senegal'),
('Paredes','Leandro','Midfielder',1.8,'Argentina'),
('Lovren','Dejan','Defender',1.88,'Croatia'),
('Hernández','Lucas','Defender',1.84,'France'),
('Comert','Eray','Defender',1.83,'Switzerland'),
('Tchouaméni','Aurélien','Midfielder',1.88,'France'),
('Kawashima','Eiji','Goalkeeper',1.85,'Japan'),
('Ramos','Goncalo','Forward',1.85,'Portugal'),
('Kohn','Philipp','Goalkeeper',1.9,'Switzerland'),
('Gomis','Alfred','Goalkeeper',1.96,'Senegal'),
('Milik','Arkadiusz','Forward',1.86,'Poland'),
('Ounahi','Azzedine','Midfielder',1.82,'Morocco'),
('Samed','Salis Abdul','Midfielder',1.79,'Ghana'),
('Ngapandouetnbu','Simon','Goalkeeper',1.86,'Cameroon'),
('Veretout','Jordan','Midfielder',1.77,'France'),
('Aboukhlal','Zakaria','Forward',1.79,'Morocco'),
('Ramsey','Aaron','Midfielder',1.78,'Wales'),
('Dembele','Ousmane','Forward',1.78,'France'),
('Dari','Achraf','Defender',1.88,'Morocco'),
('Wooh','Christopher','Defender',1.91,'Cameroon'),
('Castelletto','Jean-Charles','Defender',1.86,'Cameroon'),
('Ugarte','Manuel','Midfielder',1.82,'Uruguay'),
('Fofana','Youssouf','Midfielder',1.85,'France'),
('Mbappé','Kylian','Forward',1.78,'France'),
('da Silva Santos Junior','Neymar','Forward',1.75,'Brazil'),
('Seidu','Alidu','Defender',1.73,'Ghana'),
('Khazri','Wahbi','Forward',1.76,'Tunisia'),
('Openda','Lois','Forward',1.77,'Belgium'),
('Hakimi','Achraf','Defender',1.81,'Morocco'),
('Wieteska','Mateusz','Defender',1.87,'Poland'),
('Tagliafico','Nicolas','Defender',1.72,'Argentina'),
('Djiku','Alexander','Defender',1.82,'Ghana'),
('Embolo','Breel','Forward',1.87,'Switzerland'),
('Talbi','Montassar','Defender',1.9,'Tunisia'),
('Gueye','Pape','Midfielder',1.89,'Senegal'),
('Theate','Arthur','Defender',1.85,'Belgium'),
('Mensah','Gideon','Defender',1.78,'Ghana'),
('Corréa','Marcos Aoas','Defender',1.83,'Brazil'),
('Majer','Lovro','Midfielder',1.78,'Croatia'),
('Dieng','Bamba','Forward',1.78,'Senegal'),
('Jakobs','Ismail','Midfielder',1.84,'Senegal'),
('Porozo','Jackson','Defender',1.92,'Ecuador'),
('Mandanda','Steve','Goalkeeper',1.87,'France'),
('Pereira','Danilo','Midfielder',1.88,'Portugal'),
('Soler','Carlos','Midfielder',1.8,'Spain'),
('Diatta','Krepin','Forward',1.75,'Senegal'),
('Rieder','Fabian','Midfielder',1.81,'Switzerland'),
('Guendouzi','Mattéo','Midfielder',1.85,'France'),
('Mendy','Formose','Defender',1.91,'Senegal'),
('Muani','Randal Kolo','Forward',1.87,'France'),
('Ekambi','Karl Toko','Forward',1.82,'Cameroon'),
('Ugbo','Iké','Forward',1.84,'Canada'),
('Maria','Angel Di','Forward',1.8,'Argentina'),
('Boufal','Sofiane','Forward',1.75,'Morocco'),
('Bukari','Osman','Forward',1.7,'Ghana'),
('David','Jonathan','Forward',1.75,'Canada'),
('Dolberg','Kasper','Forward',1.87,'Denmark'),
('Kunde','Pierre','Midfielder',1.8,'Cameroon'),
('Kyereh','Daniel-Kofi','Midfielder',1.79,'Ghana'),
('Adeyemi','Karim','Forward',1.8,'Germany'),
('Sommer','Yann','Goalkeeper',1.83,'Switzerland'),
('Juranovic','Josip','Defender',1.73,'Croatia'),
('Mazraoui','Noussair','Defender',1.83,'Morocco'),
('Laidouni','Aissa','Midfielder',1.81,'Tunisia'),
('Neuer','Manuel','Goalkeeper',1.93,'Germany'),
('Hazard','Thorgan','Forward',1.75,'Belgium'),
('Choupo-Moting','Eric Maxim','Forward',1.91,'Cameroon'),
('Piatek','Krzysztof','Forward',1.83,'Poland'),
('Azmoun','Sardar','Forward',1.86,'Iran'),
('Trapp','Kevin','Goalkeeper',1.89,'Germany'),
('Poulsen','Yussuf','Forward',1.92,'Denmark'),
('Kaminski','Jakub','Forward',1.79,'Poland'),
('Blind','Daley','Defender',1.8,'Netherlands'),
('Klostermann','Lukas','Defender',1.89,'Germany'),
('Raum','David','Defender',1.8,'Germany'),
('Günter','Christian','Defender',1.84,'Germany'),
('Goretzka','Leon','Midfielder',1.89,'Germany'),
('Pavard','Benjamin','Defender',1.86,'France'),
('Guerreiro','Raphaël','Defender',1.7,'Portugal'),
('Ginter','Matthias','Defender',1.91,'Germany'),
('Wind','Jonas','Forward',1.9,'Denmark'),
('Gumny','Robert','Defender',1.82,'Poland'),
('Jakic','Kristijan','Midfielder',1.81,'Croatia'),
('Veljkovic','Milos','Defender',1.88,'Serbia'),
('Müller','Thomas','Forward',1.85,'Germany'),
('Pacho','William','Defender',1.87,'Ecuador'),
('Süle','Niklas','Defender',1.95,'Germany'),
('Sané','Leroy','Forward',1.83,'Germany'),
('Steffen','Renato','Forward',1.7,'Switzerland'),
('Kobel','Gregor','Goalkeeper',1.94,'Switzerland'),
('Kramaric','Andrej','Forward',1.77,'Croatia'),
('Hrustic','Ajdin','Forward',1.8,'Australia'),
('Thuram','Marcus','Forward',1.92,'France'),
('Lee','Jae-sung','Forward',1.8,'South Korea'),
('Hincapie','Piero','Defender',1.83,'Ecuador'),
('Lewandowski','Robert','Forward',1.85,'Poland'),
('Stanisic','Josip','Defender',1.87,'Croatia'),
('Coman','Kingsley','Forward',1.81,'France'),
('Witsel','Axel','Midfielder',1.86,'Belgium'),
('Christensen','Oliver','Goalkeeper',1.9,'Denmark'),
('Kimmich','Joshua','Midfielder',1.77,'Germany'),
('Olmo','Dani','Forward',1.79,'Spain'),
('Bellingham','Jude','Midfielder',1.86,'England'),
('Rönnow','Frederik','Goalkeeper',1.88,'Denmark'),
('Sosa','Borna','Defender',1.87,'Croatia'),
('Casteels','Koen','Goalkeeper',1.97,'Belgium'),
('Jeong','Woo-yeong','Forward',1.79,'South Korea'),
('Palacios','Exequiel','Midfielder',1.77,'Argentina'),
('Lindström','Jesper','Forward',1.82,'Denmark'),
('Itakura','Ko','Defender',1.88,'Japan'),
('Fullkrug','Niclas','Forward',1.89,'Germany'),
('Hofmann','Jonas','Forward',1.76,'Germany'),
('Davies','Alphonso','Defender',1.85,'Canada'),
('Delaney','Thomas','Midfielder',1.82,'Denmark'),
('Frimpong','Jeremie','Defender',1.71,'Netherlands'),
('Upamecano','Dayot','Defender',1.86,'France'),
('Fernandes','Edimilson','Midfielder',1.9,'Switzerland'),
('Doan','Ritsu','Forward',1.72,'Japan'),
('Widmer','Silvan','Defender',1.83,'Switzerland'),
('Musiala','Jamal','Forward',1.84,'Germany'),
('Sow','Djibril','Midfielder',1.84,'Switzerland'),
('Moukoko','Youssoufa','Forward',1.79,'Germany'),
('Vargas','Rubén','Forward',1.79,'Switzerland'),
('Brandt','Julian','Forward',1.85,'Germany'),
('Kim','Min-Jae','Defender',1.9,'South Korea'),
('Skhiri','Ellyes','Midfielder',1.85,'Tunisia'),
('Maehle','Joakim','Defender',1.85,'Denmark'),
('Ito','Hiroki','Defender',1.88,'Japan'),
('Schlotterbeck','Nico','Defender',1.91,'Germany'),
('Reyna','Giovanni','Forward',1.85,'USA'),
('De Ligt','Matthijs','Defender',1.89,'Netherlands'),
('Meunier','Thomas','Defender',1.91,'Belgium'),
('Gnabry','Serge','Forward',1.76,'Germany'),
('Elvedi','Nico','Defender',1.89,'Switzerland'),
('Götze','Mario','Midfielder',1.76,'Germany'),
('Kostic','Filip','Midfielder',1.84,'Serbia'),
('Skov','Robert','Forward',1.85,'Denmark'),
('Silva','André','Forward',1.85,'Portugal'),
('Scally','Joe','Defender',1.84,'USA'),
('Janssen','Vincent','Forward',1.85,'Netherlands'),
('Pineda','Orbelín','Forward',1.69,'Mexico'),
('Alves','Dani','Defender',1.72,'Brazil'),
('Sánchez','Jorge','Defender',1.75,'Mexico'),
('Montes','César','Defender',1.95,'Mexico'),
('Gutierrez','Erick','Midfielder',1.81,'Mexico'),
('Funes Mori','Rogelio','Forward',1.86,'Mexico'),
('Álvarez','Kevin','Defender',1.78,'Mexico'),
('Moreno','Héctor','Defender',1.86,'Mexico'),
('Ochoa','Guillermo','Goalkeeper',1.83,'Mexico'),
('Preciado','Ayrton','Forward',1.81,'Ecuador'),
('Torres','Félix','Defender',1.87,'Ecuador'),
('Mena','Ángel','Forward',1.68,'Ecuador'),
('Campbell','Joel','Forward',1.78,'Costa Rica'),
('Ibarra','Romario','Forward',1.76,'Ecuador'),
('Cota','Rodolfo','Goalkeeper',1.83,'Mexico'),
('Chávez','Luis','Midfielder',1.78,'Mexico'),
('Talavera','Alfredo','Goalkeeper',1.88,'Mexico'),
('Vega','Alexis','Forward',1.73,'Mexico'),
('Rodríguez','Carlos','Midfielder',1.71,'Mexico'),
('Gallardo','Jesús','Defender',1.76,'Mexico'),
('Martín','Henry','Forward',1.77,'Mexico'),
('Drager','Mohamed','Defender',1.81,'Tunisia'),
('Smith','Matt','Midfielder',1.75,'Wales'),
('Ntcham','Olivier','Midfielder',1.8,'Cameroon'),
('Fatawu','Issahaku','Midfielder',1.77,'Ghana'),
('Fassnacht','Christian','Midfielder',1.85,'Switzerland'),
('Harris','Mark','Forward',1.82,'Wales'),
('Loum','Mamadou','Midfielder',1.88,'Senegal'),
('Wright','Bailey','Defender',1.84,'Australia'),
('Thomas','Sorba','Forward',1.85,'Wales'),
('Baba','Abdul Rahman','Defender',1.79,'Ghana'),
('McGree','Riley','Midfielder',1.78,'Australia'),
('Bielik','Krystian','Midfielder',1.89,'Poland'),
('Colwill','Rubin','Midfielder',1.89,'Wales'),
('Chair','Ilias','Midfielder',1.71,'Morocco'),
('Cabango','Ben','Defender',1.86,'Wales'),
('Millar','Liam','Forward',1.81,'Canada'),
('Dieng','Timothy','Goalkeeper',1.93,'Senegal'),
('Allen','Joe','Midfielder',1.7,'Wales'),
('Wright','Haji','Forward',1.93,'USA'),
('Bennette','Jewison','Forward',1.73,'Costa Rica'),
('Guardado','Andres','Midfielder',1.67,'Mexico'),
('Sosa','Sebastian','Goalkeeper',1.81,'Uruguay'),
('Mignolet','Simon','Goalkeeper',1.93,'Belgium'),
('De Roon','Marten','Midfielder',1.85,'Netherlands'),
('N"Koudou','Georges-Kevin','Forward',1.72,'Cameroon'),
('Gómez','Papu','Midfielder',1.67,'Argentina'),
('Pasalic','Mario','Midfielder',1.88,'Croatia'),
('Maeda','Daizen','Forward',1.73,'Japan'),
('da Silva','Otavio','Midfielder',1.72,'Portugal'),
('Koopmeiners','Teun','Midfielder',1.83,'Netherlands'),
('Cornelius','Andreas','Forward',1.93,'Denmark'),
('Wass','Daniel','Defender',1.78,'Denmark'),
('Dybala','Paulo','Forward',1.77,'Argentina'),
('Sucic','Luka','Midfielder',1.85,'Croatia'),
('Muslera','Fernando','Goalkeeper',1.9,'Uruguay'),
('Hernandez','Theo','Defender',1.84,'France'),
('de Jong','Frenkie','Midfielder',1.81,'Netherlands'),
('Vanaken','Hans','Midfielder',1.95,'Belgium'),
('Bah','Alexander','Defender',1.83,'Denmark'),
('Sandro','Alex','Defender',1.81,'Brazil'),
('Bijlow','Justin','Goalkeeper',1.88,'Netherlands'),
('Mertens','Dries','Forward',1.69,'Belgium'),
('Rulli','Gerónimo','Goalkeeper',1.89,'Argentina'),
('Acuña','Marcos','Defender',1.72,'Argentina'),
('Carrasco','Yannick','Forward',1.81,'Belgium'),
('Musah','Yunus','Midfielder',1.78,'USA'),
('Aebischer','Michel','Midfielder',1.83,'Switzerland'),
('Vida','Domagoj','Defender',1.84,'Croatia'),
('Foyth','Juan','Defender',1.87,'Argentina'),
('Szczesny','Wojciech','Goalkeeper',1.96,'Poland'),
('Pasveer','Remko','Goalkeeper',1.87,'Netherlands'),
('Ngamaleu','Nicolas','Forward',1.81,'Cameroon'),
('Vecino','Matias','Midfielder',1.87,'Uruguay'),
('En-Nesyri','Youssef','Forward',1.92,'Morocco'),
('Rabiot','Adrien','Midfielder',1.88,'France'),
('Vlahović','Dušan','Forward',1.9,'Serbia'),
('Suarez','Luis','Forward',1.82,'Uruguay'),
('Zielinski','Piotr','Midfielder',1.8,'Poland'),
('Grabara','Kamil','Goalkeeper',1.95,'Poland'),
('Coates','Sebastian','Defender',1.96,'Uruguay'),
('De Ketelaere','Charles','Midfielder',1.92,'Belgium'),
('Luiz da Silva','Danilo','Defender',1.84,'Brazil'),
('Sowah','Kamal','Forward',1.79,'Ghana'),
('Kounde','Jules','Defender',1.8,'France'),
('Courtois','Thibaut','Goalkeeper',2,'Belgium'),
('Carter-Vickers','Cameron','Defender',1.83,'USA'),
('ter Stegen','Marc-Andre ','Goalkeeper',1.87,'Germany'),
('Lopez','Pedro','Forward',1.74,'Spain'),
('Costa','Diogo','Goalkeeper',1.86,'Portugal'),
('Martinez','Lautaro','Forward',1.74,'Argentina'),
('Taylor','Kenneth','Midfielder',1.82,'Netherlands'),
('Vertonghen','Jan','Defender',1.89,'Belgium'),
('Okafor','Noah','Forward',1.85,'Switzerland'),
('Gavira','Pablo','Midfielder',1.73,'Spain'),
('Larin','Cyle','Forward',1.88,'Canada'),
('Lang','Noa','Forward',1.7,'Netherlands'),
('Ferreira','Képler','Defender',1.87,'Portugal'),
('Molina','Nahuel','Defender',1.75,'Argentina'),
('Gimenez','Jose','Defender',1.85,'Uruguay'),
('Grujic','Marko','Midfielder',1.91,'Serbia'),
('Eustaquio','Stephen','Midfielder',1.77,'Canada'),
('de Goes','Rodrygo','Forward',1.74,'Brazil'),
('Ueda','Ayase','Forward',1.82,'Japan'),
('Balde','Alex','Defender',1.75,'Spain'),
('Depay','Memphis','Forward',1.78,'Netherlands'),
('Pino','Yeremi','Forward',1.72,'Spain'),
('Dia','Boulaye','Forward',1.8,'Senegal'),
('Hutchinson','Atiba','Midfielder',1.87,'Canada'),
('Kjaer','Simon','Defender',1.91,'Denmark'),
('Merodio','Jorge','Midfielder',1.76,'Spain'),
('Llorente','Marcos','Midfielder',1.84,'Spain'),
('Dmitrovic','Marko','Goalkeeper',1.89,'Serbia'),
('Jovic','Luka','Forward',1.82,'Serbia'),
('Tadić','Dusan','Forward',1.81,'Serbia'),
('Correa','Angel','Forward',1.71,'Argentina'),
('Valverde','Federico','Midfielder',1.82,'Uruguay'),
('Silva','Antonio','Defender',1.87,'Portugal'),
('De Vrij','Stefan','Defender',1.89,'Netherlands'),
('Gudelj','Nemanja','Midfielder',1.87,'Serbia'),
('Horta','Ricardo','Forward',1.73,'Portugal'),
('de Paul','Rodrigo','Midfielder',1.8,'Argentina'),
('de Jong','Luuk','Forward',1.88,'Netherlands'),
('Dumfries','Denzel','Midfielder',1.88,'Netherlands'),
('Torreira','Lucas','Midfielder',1.66,'Uruguay'),
('Mario','Joao','Midfielder',1.79,'Portugal'),
('Hwang','In-beom','Midfielder',1.77,'South Korea'),
('Leao','Rafael','Forward',1.88,'Portugal'),
('Berghuis','Steven','Midfielder',1.82,'Netherlands'),
('Bounou','Yassine','Goalkeeper',1.92,'Morocco'),
('Dest','Sergiño','Defender',1.71,'USA'),
('Taremi','Mehdi','Forward',1.85,'Iran'),
('Nsame','Jean Pierre','Forward',1.88,'Cameroon'),
('Nelsson','Victor','Defender',1.85,'Denmark'),
('Klaassen','Davy','Midfielder',1.79,'Netherlands'),
('Carvajal','Daniel','Defender',1.73,'Spain'),
('Militao','Eder','Defender',1.86,'Brazil'),
('Junior','Vinícius','Forward',1.76,'Brazil'),
('Olivera','Mathí­as','Defender',1.85,'Uruguay'),
('Griezmann','Antoine','Forward',1.76,'France'),
('Brozovic','Marcelo','Midfielder',1.81,'Croatia'),
('Modric','Luka','Midfielder',1.72,'Croatia'),
('Seferovic','Haris','Forward',1.89,'Switzerland'),
('Hazard','Eden','Forward',1.75,'Belgium'),
('Morrell','Joe','Midfielder',1.85,'Wales'),
('Williams','Jonathan','Midfielder',1.68,'Wales'),
('Racic','Uros','Midfielder',1.93,'Serbia'),
('El Yamiq','Jawad','Defender',1.93,'Morocco'),
('Amallah','Selim','Midfielder',1.86,'Morocco'),
('Williams','Inaki','Forward',1.86,'Ghana'),
('Mabil','Awer','Forward',1.78,'Australia'),
('Plata','Gonzalo','Forward',1.78,'Ecuador'),
('Diedhiou','Famara','Forward',1.89,'Senegal'),
('Gomez','Maxi','Forward',1.86,'Uruguay'),
('Braithwaite','Martin','Forward',1.77,'Denmark'),
('Rodríguez','Guido','Midfielder',1.85,'Argentina'),
('Hongla','Martin','Midfielder',1.81,'Cameroon'),
('Pezzella','German','Defender',1.87,'Argentina'),
('Simon','Unai','Goalkeeper',1.9,'Spain'),
('Ezzalzouli','Abde','Forward',1.77,'Morocco'),
('Ciss','Pathe','Midfielder',1.86,'Senegal'),
('Aidoo','Joseph','Defender',1.77,'Ghana'),
('Carvalho','William','Midfielder',1.87,'Portugal'),
('Mitrovic','Stefan','Defender',1.89,'Serbia'),
('Budimir','Ante','Forward',1.9,'Croatia'),
('Maksimovic','Nemanja','Midfielder',1.84,'Serbia'),
('Sabaly','Youssouf','Defender',1.73,'Senegal'),
('Babic','Srdjan','Defender',1.94,'Serbia'),
('Williams','Nico','Forward',1.81,'Spain'),
('Guillamon','Hugo','Defender',1.78,'Spain'),
('De La Torre','Luca','Midfielder',1.77,'USA'),
('Kechrida','Wajdi','Midfielder',1.84,'Tunisia'),
('Skorupski','Lukasz','Goalkeeper',1.87,'Poland'),
('Ilić','Ivan','Midfielder',1.85,'Serbia'),
('Zurkowski','Szymon','Midfielder',1.85,'Poland'),
('Bereszynski','Bartosz','Defender',1.83,'Poland'),
('Zalewski','Nicola','Midfielder',1.75,'Poland'),
('Bremer','Gleison','Defender',1.88,'Brazil'),
('Milinković-Savić','Sergej','Midfielder',1.91,'Serbia'),
('Rodriguez2','Ricardo','Defender',1.8,'Switzerland'),
('Djuricic','Filip','Midfielder',1.81,'Serbia'),
('Milenkovic','Nikola','Defender',1.95,'Serbia'),
('Lazović','Darko','Midfielder',1.81,'Serbia'),
('Milinković-Savić','Vanja','Goalkeeper',2.02,'Serbia'),
('Sabiri','Abdelhamid','Midfielder',1.86,'Morocco'),
('Erlic','Martin','Defender',1.93,'Croatia'),
('Cheddira','Walid','Forward',1.87,'Morocco'),
('Vásquez','Johan','Defender',1.85,'Mexico'),
('Ondoua','Gael','Midfielder',1.85,'Cameroon'),
('Tanaka','Ao','Midfielder',1.8,'Japan'),
('Machino','Shuto','Forward',1.85,'Japan'),
('Irvine','Jackson','Midfielder',1.89,'Australia'),
('Owusu','Elisha','Midfielder',1.82,'Ghana'),
('Abdi','Ali','Defender',1.83,'Tunisia'),
('Hajsafi','Ehsan','Defender',1.78,'Iran'),
('Al-Rawi','Bassam','Defender',1.75,'Qatar'),
('Ezatolahi','Saeid','Midfielder',1.9,'Iran'),
('Zamora','Alvaro','Midfielder',1.8,'Costa Rica'),
('Kim','Seun-gyu','Goalkeeper',1.87,'South Korea'),
('Mohammadi','Milad','Defender',1.78,'Iran'),
('Reasco','Djorkaeff','Forward',1.72,'Ecuador'),
('Al-Sheeb','Saad','Goalkeeper',1.88,'Qatar'),
('Bahebri','Hattan','Forward',1.7,'Saudi Arabia'),
('Name','Moustapha','Midfielder',1.85,'Senegal'),
('Hassen','Mouez','Goalkeeper',1.86,'Tunisia'),
('Kanno','Mohamed','Midfielder',1.92,'Saudi Arabia'),
('Muntari','Mohammed','Forward',1.94,'Qatar'),
('Venegas','Johan','Forward',1.83,'Costa Rica'),
('Kim','Tae-hwan','Defender',1.8,'South Korea'),
('Jalali','Abolfazl','Defender',1.77,'Iran'),
('Gholizadeh','Ali','Forward',1.75,'Iran'),
('Vukovic','Danny','Goalkeeper',1.87,'Australia'),
('Asad','Ali','Midfielder',1.75,'Qatar'),
('Fai','Collins','Defender',1.65,'Cameroon'),
('Afriyie','Daniel','Forward',1.65,'Ghana'),
('Al-Shahrani','Yasser','Defender',1.7,'Saudi Arabia'),
('Salman','Tarek','Defender',1.79,'Qatar'),
('Jaziri','Seifeddine','Forward',1.8,'Tunisia'),
('Al-Dawsari','Salem','Forward',1.71,'Saudi Arabia'),
('Waad','Mohammed','Midfielder',1.83,'Qatar'),
('Msakni','Youssef','Forward',1.79,'Tunisia'),
('Al-Haydos','Hasan','Forward',1.74,'Qatar'),
('Bassogog','Christian','Forward',1.73,'Cameroon'),
('Devlin','Cammy','Midfielder',1.69,'Australia'),
('De Arrascaeta','Giorgian','Midfielder',1.74,'Uruguay'),
('Levitt','Dylan','Midfielder',1.8,'Wales'),
('Livakovic','Dominik','Goalkeeper',1.88,'Croatia'),
('Ghandri','Nader','Defender',1.97,'Tunisia'),
('Balbouli','Aymen','Goalkeeper',1.82,'Tunisia'),
('Vargas','Juan Pablo','Defender',1.92,'Costa Rica'),
('Tambakti','Hassan','Defender',1.82,'Saudi Arabia'),
('Sliti','Naim','Forward',1.73,'Tunisia'),
('Yamane','Miki','Defender',1.78,'Japan'),
('Vitoria','Steven','Defender',1.95,'Canada'),
('Hosseini','Hossein','Goalkeeper',1.87,'Iran'),
('Lopez','Douglas','Midfielder',1.8,'Costa Rica'),
('Ifa','Bilel','Defender',1.85,'Tunisia'),
('Madibo','Assim','Midfielder',1.68,'Qatar'),
('Asiri','Haitham','Forward',1.73,'Saudi Arabia'),
('Cissé','Pape Abou','Defender',1.98,'Senegal'),
('Duarte','Óscar','Defender',1.86,'Costa Rica'),
('Hatem','Abdulaziz','Midfielder',1.83,'Qatar'),
('Paik','Seung-ho','Midfielder',1.82,'South Korea'),
('Redmayne','Andrew','Goalkeeper',1.94,'Australia'),
('Chaaleli','Ghaylen','Midfielder',1.79,'Tunisia'),
('Otayf','Abdullah','Midfielder',1.77,'Saudi Arabia'),
('Nagatomo','Yuto','Defender',1.7,'Japan'),
('Ansarifard','Karim','Forward',1.86,'Iran'),
('Afif','Akram','Forward',1.77,'Qatar'),
('Skoras','Michal','Forward',1.72,'Poland'),
('Marou','Souaibou','Forward',1.8,'Cameroon'),
('Boudiaf','Karim','Midfielder',1.87,'Qatar'),
('Contreras','Anthony','Forward',1.8,'Costa Rica'),
('Son','Jun-ho','Midfielder',1.78,'South Korea'),
('Zivkovic','Andrija','Forward',1.69,'Serbia'),
('Pouraliganji','Morteza','Defender',1.85,'Iran'),
('Al-Hajri','Salem','Midfielder',1.83,'Qatar'),
('Erakovic','Strahinja','Defender',1.88,'Serbia'),
('Petkovic','Bruno','Forward',1.93,'Croatia'),
('Frei','Fabian','Midfielder',1.83,'Switzerland'),
('Mazeed','Khalid Muneer','Forward',1.74,'Qatar'),
('Gunter','Chris','Defender',1.8,'Wales'),
('Dahmen','Aymen','Goalkeeper',1.88,'Tunisia'),
('Ahmed','Homam','Defender',1.86,'Qatar'),
('N"Diaye','Moussa','Defender',1.81,'Senegal'),
('Hassan','Yousef','Goalkeeper',1.86,'Qatar'),
('Song','Min-kyu','Forward',1.81,'South Korea'),
('Mbekeli','Jerome','Forward',1.75,'Cameroon'),
('Deng','Thomas','Defender',1.78,'Australia'),
('Al-Aqidi','Nawaf','Goalkeeper',1.86,'Saudi Arabia'),
('Mohammed','Ismaeel','Forward',1.68,'Qatar'),
('Borjan','Milan','Goalkeeper',1.96,'Canada'),
('Kim','Jin-su','Defender',1.77,'South Korea'),
('Barsham','Meshaal','Goalkeeper',1.8,'Qatar'),
('Sassi','Ferjani','Midfielder',1.85,'Tunisia'),
('Sharahili','Riad','Midfielder',1.85,'Saudi Arabia'),
('Karimi','Ali','Midfielder',1.85,'Iran'),
('Al-Faraj','Salman','Midfielder',1.8,'Saudi Arabia'),
('Niazmand','Payam','Goalkeeper',1.94,'Iran'),
('Atkinson','Nathaniel','Defender',1.81,'Australia'),
('Na','Sang-ho','Forward',1.73,'South Korea'),
('Tagnaouti','Ahmed Reda','Goalkeeper',1.92,'Morocco'),
('Martinez','Carlos','Defender',1.75,'Costa Rica'),
('Rodriguez','Kevin','Forward',1.9,'Ecuador'),
('Kuol','Garang','Forward',1.75,'Australia'),
('Rowles','Kye','Defender',1.85,'Australia'),
('Taniguchi','Shogo','Defender',1.83,'Japan'),
('Khenissi','Taha Yassine','Forward',1.8,'Tunisia'),
('Szymanski','Damian','Midfielder',1.85,'Poland'),
('Al-Hassan','Ali','Midfielder',1.76,'Saudi Arabia'),
('Jedrzejczyk','Artur','Defender',1.89,'Poland'),
('Benoun','Badr','Defender',1.93,'Morocco'),
('Khoder','Musab','Defender',1.76,'Qatar'),
('Khalilzadeh','Shoja','Defender',1.8,'Iran'),
('Stryger Larsen','Jens','Defender',1.82,'Denmark'),
('Chacon','Daniel','Midfielder',1.83,'Costa Rica'),
('Jabrane','Yahya','Midfielder',1.87,'Morocco'),
('Wilson','Roan','Midfielder',1.84,'Costa Rica'),
('Aboubakar','Vincent','Forward',1.84,'Cameroon'),
('Hosseini','Majid','Defender',1.87,'Iran'),
('Miguel','Pedro','Defender',1.82,'Qatar'),
('Leckie','Mathew','Forward',1.81,'Australia'),
('Maaloul','Ali','Defender',1.75,'Tunisia'),
('Duke','Mitchell','Forward',1.86,'Australia'),
('Waston','Kendall','Defender',1.96,'Costa Rica'),
('Al-Najei','Sami','Midfielder',1.76,'Saudi Arabia'),
('Al-Shehri','Saleh','Forward',1.84,'Saudi Arabia'),
('Sutalo','Josip','Defender',1.9,'Croatia'),
('Maclaren','Jamie','Forward',1.79,'Australia'),
('Armani','Franco','Goalkeeper',1.89,'Argentina'),
('El Khannouss','Bilal','Midfielder',1.8,'Morocco'),
('Mashaal','Mustafa','Midfielder',1.74,'Qatar'),
('Beiranvand','Alireza','Goalkeeper',1.94,'Iran'),
('Godin','Diego','Defender',1.87,'Uruguay'),
('Al-Rubaie','Mohammed','Goalkeeper',1.9,'Saudi Arabia'),
('Noppert','Andries','Goalkeeper',2.03,'Netherlands'),
('Abedzadeh','Amir','Goalkeeper',1.86,'Iran'),
('Preciado','Angelo','Defender',1.73,'Ecuador'),
('Wotherspoon','David','Midfielder',1.72,'Canada'),
('Hassan','Abdelkarim','Defender',1.86,'Qatar'),
('Salas','Youstin','Midfielder',1.73,'Costa Rica'),
('Khoukhi','Boualem','Defender',1.8,'Qatar'),
('Kim','Young-gwon','Defender',1.86,'South Korea'),
('Borges','Celso','Midfielder',1.82,'Costa Rica'),
('Al-Oboud','Abdulrahman','Forward',1.74,'Saudi Arabia'),
('Al-Bulayhi','Ali','Defender',1.82,'Saudi Arabia'),
('Cheshmi','Roozbeh','Midfielder',1.94,'Iran'),
('Oum Gouet','Samuel','Midfielder',1.85,'Cameroon'),
('Dominguez','Alexander','Goalkeeper',1.95,'Ecuador'),
('Hong','Chul','Defender',1.76,'South Korea'),
('Attiat-Allah','Yahia','Defender',1.76,'Morocco'),
('Al-Amri','Abdulelah','Defender',1.83,'Saudi Arabia'),
('Krychowiak','Grzegorz','Midfielder',1.87,'Poland'),
('Barisic','Borna','Defender',1.86,'Croatia'),
('Rodríguez','José Luis','Defender',1.83,'Uruguay'),
('Ribeiro','Everton','Midfielder',1.74,'Brazil'),
('Galindez','Hernan','Goalkeeper',1.89,'Ecuador'),
('King','Joel','Defender',1.79,'Australia'),
('Ivusic','Ivica','Goalkeeper',1.95,'Croatia'),
('Epassy','Devis','Goalkeeper',1.89,'Cameroon'),
('Varela','Guillermo','Defender',1.73,'Uruguay'),
('Jung','Woo-young','Midfielder',1.86,'South Korea'),
('Cummings','Jason','Forward',1.78,'Australia'),
('Ruiz','Bryan','Midfielder',1.87,'Costa Rica'),
('Rezaeian','Ramin','Defender',1.85,'Iran'),
('Morita','Hidemasa','Midfielder',1.77,'Japan'),
('Canobbio','Agustin','Forward',1.75,'Uruguay'),
('Cho','Gue-sung','Forward',1.89,'South Korea'),
('Tejeda','Yeltsin','Midfielder',1.79,'Costa Rica'),
('Mladenovic','Filip','Midfielder',1.8,'Serbia'),
('Ati Zigi','Lawrence','Goalkeeper',1.88,'Ghana'),
('Arboleda','Robert','Defender',1.89,'Ecuador'),
('Al-Hadhrami','Naif','Forward',1.8,'Qatar'),
('Jashari','Ardon','Midfielder',1.81,'Switzerland'),
('Meriah','Yassine','Defender',1.88,'Tunisia'),
('Ben Romdhane','Mohamed Ali','Midfielder',1.85,'Tunisia'),
('Al-Abed','Nawaf','Midfielder',1.7,'Saudi Arabia'),
('Szymanski','Sebastian','Midfielder',1.74,'Poland'),
('Guilherme','Pedro','Forward',1.85,'Brazil'),
('Al-Malki','Abdulelah','Midfielder',1.7,'Saudi Arabia'),
('Rochet','Sergio','Goalkeeper',1.9,'Uruguay'),
('Jo','Hyeon-woo','Goalkeeper',1.89,'South Korea'),
('Moharrami','Sadegh','Defender',1.74,'Iran'),
('Goodwin','Craig','Forward',1.83,'Australia'),
('Al-Ghannam','Sultan','Defender',1.73,'Saudi Arabia'),
('Torabi','Mehdi','Forward',1.8,'Iran'),
('Abdulhamid','Saud','Defender',1.75,'Saudi Arabia'),
('Torres','Gerson','Midfielder',1.71,'Costa Rica'),
('Cho','Yu-min','Defender',1.85,'South Korea'),
('Skov Olsen','Andreas','Midfielder',1.87,'Denmark'),
('Livaja','Marko','Forward',1.84,'Croatia'),
('Kwon','Chang-hoon','Forward',1.73,'South Korea'),
('De La Cruz','Nicolas','Midfielder',1.67,'Uruguay'),
('Abdulsallam','Jassem Gaber','Defender',1.83,'Qatar'),
('Glik','Kamil','Defender',1.9,'Poland'),
('Al-Dawsari','Nasser','Defender',1.78,'Saudi Arabia'),
('Kanaani','Hossein','Defender',1.88,'Iran'),
('Valencia','Enner','Forward',1.77,'Ecuador'),
('Al-Buraikan','Firas','Forward',1.81,'Saudi Arabia'),
('Nourollahi','Ahmad','Midfielder',1.85,'Iran'),
('Alaaeldin','Ahmed','Forward',1.77,'Qatar'),
('Danlad','Ibrahim','Goalkeeper',1.81,'Ghana'),
('Ramirez','Moises','Goalkeeper',1.85,'Ecuador'),
('Tilio','Marco','Forward',1.7,'Australia'),
('Al-Owais','Mohammed','Goalkeeper',1.85,'Saudi Arabia'),
('Amiri','Vahid','Forward',1.79,'Iran'),
('Al-Burayk','Mohammed','Defender',1.7,'Saudi Arabia'),
('Ben Said','Bechir','Goalkeeper',1.94,'Tunisia'),
('Alvarado','Esteban','Goalkeeper',1.93,'Costa Rica'),
('Yoon','Jong-gyu','Defender',1.73,'South Korea'),
('Mooy','Aaron','Midfielder',1.74,'Australia'),
('Gonda','Shuichi','Goalkeeper',1.87,'Japan'),
('Kwon','Kyung-won','Defender',1.89,'South Korea'),
('Hamdallah','Abderrazak','Forward',1.82,'Morocco'),
('Pereira da Silva','Weverton','Goalkeeper',1.89,'Brazil'),
('Madu','Abdullah','Defender',1.86,'Saudi Arabia'),
('Baccus','Keanu','Midfielder',1.78,'Australia'),
('Song','Bum-keun','Goalkeeper',1.94,'South Korea'),
('Hernandez','Anthony','Forward',1.79,'Costa Rica'),
('Debast','Zeno','Defender',1.91,'Belgium'),
('Ali','Almoez','Forward',1.8,'Qatar'),
('Behich','Aziz','Defender',1.7,'Australia'),
('Sequeira','Patrick','Goalkeeper',1.9,'Costa Rica'),
('Nurudeen','Abdul','Goalkeeper',1.89,'Ghana'),
('Jebali','Issam','Forward',1.86,'Tunisia'),
('Arteaga','Gerardo','Defender',1.75,'Mexico'),
('El Kajoui','Munir','Goalkeeper',1.9,'Morocco'),
('Soma','Yuki','Forward',1.66,'Japan'),
('Fuller','Keysher','Defender',1.83,'Costa Rica'),
('Karacic','Fran','Defender',1.81,'Australia');

-- =========================================================
-- Insert Matches 
-- =========================================================
INSERT INTO Match (round, date, venue_name) VALUES
('Group Stage', '2022-11-20', 'Al Bayt Stadium'),
('Group Stage', '2022-11-21', 'Al Thumama Stadium'),
('Group Stage', '2022-11-25', 'Al Thumama Stadium'),
('Group Stage', '2022-11-25', 'Khalifa International Stadium'),
('Group Stage', '2022-11-29', 'Khalifa International Stadium'),
('Group Stage', '2022-11-29', 'Al Bayt Stadium'),
('Group Stage', '2022-11-21', 'Khalifa International Stadium'),
('Group Stage', '2022-11-21', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-11-25', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-11-25', 'Al Bayt Stadium'),
('Group Stage', '2022-11-29', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-11-29', 'Al Thumama Stadium'),
('Group Stage', '2022-11-22', 'Lusail Stadium'),
('Group Stage', '2022-11-22', 'Stadium 974'),
('Group Stage', '2022-11-26', 'Education City Stadium'),
('Group Stage', '2022-11-26', 'Lusail Stadium'),
('Group Stage', '2022-11-30', 'Stadium 974'),
('Group Stage', '2022-11-30', 'Lusail Stadium'),
('Group Stage', '2022-11-22', 'Education City Stadium'),
('Group Stage', '2022-11-22', 'Al Janoub Stadium'),
('Group Stage', '2022-11-26', 'Al Janoub Stadium'),
('Group Stage', '2022-11-26', 'Stadium 974'),
('Group Stage', '2022-11-30', 'Al Janoub Stadium'),
('Group Stage', '2022-11-30', 'Education City Stadium'),
('Group Stage', '2022-11-23', 'Khalifa International Stadium'),
('Group Stage', '2022-11-23', 'Al Thumama Stadium'),
('Group Stage', '2022-11-27', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-11-27', 'Al Bayt Stadium'),
('Group Stage', '2022-12-01', 'Khalifa International Stadium'),
('Group Stage', '2022-12-01', 'Al Bayt Stadium'),
('Group Stage', '2022-11-23', 'Al Bayt Stadium'),
('Group Stage', '2022-11-23', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-11-27', 'Al Thumama Stadium'),
('Group Stage', '2022-11-27', 'Khalifa International Stadium'),
('Group Stage', '2022-12-01', 'Ahmad Bin Ali Stadium'),
('Group Stage', '2022-12-01', 'Al Thumama Stadium'),
('Group Stage', '2022-11-24', 'Al Janoub Stadium'),
('Group Stage', '2022-11-24', 'Lusail Stadium'),
('Group Stage', '2022-11-28', 'Al Janoub Stadium'),
('Group Stage', '2022-11-28', 'Stadium 974'),
('Group Stage', '2022-12-02', 'Stadium 974'),
('Group Stage', '2022-12-02', 'Lusail Stadium'),
('Group Stage', '2022-11-24', 'Education City Stadium'),
('Group Stage', '2022-11-24', 'Stadium 974'),
('Group Stage', '2022-11-28', 'Education City Stadium'),
('Group Stage', '2022-11-28', 'Lusail Stadium'),
('Group Stage', '2022-12-02', 'Al Janoub Stadium'),
('Group Stage', '2022-12-02', 'Education City Stadium'),
('Round of 16', '2022-12-03', 'Khalifa International Stadium'),
('Round of 16', '2022-12-03', 'Ahmad Bin Ali Stadium'),
('Round of 16', '2022-12-04', 'Al Thumama Stadium'),
('Round of 16', '2022-12-04', 'Al Bayt Stadium'),
('Round of 16', '2022-12-05', 'Al Janoub Stadium'),
('Round of 16', '2022-12-05', 'Stadium 974'),
('Round of 16', '2022-12-06', 'Education City Stadium'),
('Round of 16', '2022-12-06', 'Lusail Stadium'),
('Quarter-final', '2022-12-09', 'Education City Stadium'),
('Quarter-final', '2022-12-09', 'Lusail Stadium'),
('Quarter-final', '2022-12-10', 'Al Thumama Stadium'),
('Quarter-final', '2022-12-10', 'Al Bayt Stadium'),
('Semi-final', '2022-12-13', 'Lusail Stadium'),
('Semi-final', '2022-12-14', 'Al Bayt Stadium'),
('Third place', '2022-12-17', 'Khalifa International Stadium'),
('Final', '2022-12-18', 'Lusail Stadium');

-- =========================================================
-- Insert MatchParticipant
-- =========================================================
INSERT INTO MatchParticipant (nationality, match_id) VALUES
('Qatar', 1), ('Ecuador', 1),
('Senegal', 2), ('Netherlands', 2),
('Qatar', 3), ('Senegal', 3),
('Netherlands', 4), ('Ecuador', 4),
('Ecuador', 5), ('Senegal', 5),
('Netherlands', 6), ('Qatar', 6),
('England', 7), ('Iran', 7),
('USA', 8), ('Wales', 8),
('Wales', 9), ('Iran', 9),
('England', 10), ('USA', 10),
('Wales', 11), ('England', 11),
('Iran', 12), ('USA', 12),
('Argentina', 13), ('Saudi Arabia', 13),
('Mexico', 14), ('Poland', 14),
('Poland', 15), ('Saudi Arabia', 15),
('Argentina', 16), ('Mexico', 16),
('Poland', 17), ('Argentina', 17),
('Saudi Arabia', 18), ('Mexico', 18),
('Denmark', 19), ('Tunisia', 19),
('France', 20), ('Australia', 20),
('Tunisia', 21), ('Australia', 21),
('France', 22), ('Denmark', 22),
('Australia', 23), ('Denmark', 23),
('Tunisia', 24), ('France', 24),
('Germany', 25), ('Japan', 25),
('Spain', 26), ('Costa Rica', 26),
('Japan', 27), ('Costa Rica', 27),
('Spain', 28), ('Germany', 28),
('Japan', 29), ('Spain', 29),
('Costa Rica', 30), ('Germany', 30),
('Morocco', 31), ('Croatia', 31),
('Belgium', 32), ('Canada', 32),
('Belgium', 33), ('Morocco', 33),
('Croatia', 34), ('Canada', 34),
('Croatia', 35), ('Belgium', 35),
('Canada', 36), ('Morocco', 36),
('Switzerland', 37), ('Cameroon', 37),
('Brazil', 38), ('Serbia', 38),
('Cameroon', 39), ('Serbia', 39),
('Brazil', 40), ('Switzerland', 40),
('Serbia', 41), ('Switzerland', 41),
('Cameroon', 42), ('Brazil', 42),
('Uruguay', 43), ('South Korea', 43),
('Portugal', 44), ('Ghana', 44),
('South Korea', 45), ('Ghana', 45),
('Portugal', 46), ('Uruguay', 46),
('Ghana', 47), ('Uruguay', 47),
('South Korea', 48), ('Portugal', 48),
('Netherlands', 49), ('USA', 49),
('Argentina', 50), ('Australia', 50),
('France', 51), ('Poland', 51),
('England', 52), ('Senegal', 52),
('Japan', 53), ('Croatia', 53),
('Brazil', 54), ('South Korea', 54),
('Morocco', 55), ('Spain', 55),
('Portugal', 56), ('Switzerland', 56),
('Croatia', 57), ('Brazil', 57),
('Netherlands', 58), ('Argentina', 58),
('Morocco', 59), ('Portugal', 59),
('England', 60), ('France', 60),
('Argentina', 61), ('Croatia', 61),
('France', 62), ('Morocco', 62),
('Croatia', 63), ('Morocco', 63),
('Argentina', 64), ('France', 64);

-- =========================================================
-- Insert Goals (Regular/ET)  ※ is_penalty_shootout = FALSE
-- =========================================================
INSERT INTO Goal (player_lastname, player_surname, match_id, goalTime, is_penalty_shootout) VALUES
-- GroupA
('Valencia', 'Enner', 1, '16', FALSE),
('Valencia', 'Enner', 1, '31', FALSE),
('Gakpo', 'Cody', 2, '84', FALSE),
('Klaassen', 'Davy', 2, '90+9', FALSE),
('Muntari', 'Mohammed', 3, '78', FALSE),
('Dia', 'Boulaye', 3, '41', FALSE),
('Diedhiou', 'Famara', 3, '48', FALSE),
('Dieng', 'Bamba', 3, '84', FALSE),
('Gakpo', 'Cody', 4, '6', FALSE),
('Valencia', 'Enner', 4, '49', FALSE),
('Caicedo', 'Moises', 5, '67', FALSE),
('Sarr', 'Ismaïla', 5, '44', FALSE),
('Koulibaly', 'Kalidou', 5, '70', FALSE),
('Gakpo', 'Cody', 6, '26', FALSE),
('de Jong', 'Frenkie', 6, '49', FALSE),

-- GroupB
('Bellingham', 'Jude', 7, '35', FALSE),
('Saka', 'Bukayo', 7, '43', FALSE),
('Saka', 'Bukayo', 7, '62', FALSE),
('Sterling', 'Raheem', 7, '45+1', FALSE),
('Rashford', 'Marcus', 7, '71', FALSE),
('Grealish', 'Jack', 7, '90+1', FALSE),
('Taremi', 'Mehdi', 7, '65', FALSE),
('Taremi', 'Mehdi', 7, '90+13', FALSE),
('Weah', 'Timothy', 8, '36', FALSE),
('Bale', 'Gareth', 8, '82', FALSE),
('Cheshmi', 'Roozbeh', 9, '90+8', FALSE),
('Rezaeian', 'Ramin', 9, '90+11', FALSE),
('Rashford', 'Marcus', 11, '50', FALSE),
('Rashford', 'Marcus', 11, '68', FALSE),
('Foden', 'Phil', 11, '51', FALSE),
('Pulisic', 'Christian', 12, '38', FALSE),

-- GroupC
('Messi', 'Lionel', 13, '10', FALSE),
('Al-Shehri', 'Saleh', 13, '48', FALSE),
('Al-Dawsari', 'Salem', 13, '53', FALSE),
('Zielinski', 'Piotr', 15, '39', FALSE),
('Lewandowski', 'Robert', 15, '82', FALSE),
('Messi', 'Lionel', 16, '64', FALSE),
('Fernandez', 'Enzo', 16, '87', FALSE),
('MacAllister', 'Alexis', 17, '46', FALSE),
('Alvarez', 'Julian', 17, '67', FALSE),
('Al-Dawsari', 'Salem', 18, '90+5', FALSE),
('Martín', 'Henry', 18, '47', FALSE),
('Chávez', 'Luis', 18, '52', FALSE),

-- GroupD
('Rabiot', 'Adrien', 20, '27', FALSE),
('Giroud', 'Olivier', 20, '32', FALSE),
('Giroud', 'Olivier', 20, '71', FALSE),
('Mbappé', 'Kylian', 20, '68', FALSE),
('Goodwin', 'Craig', 20, '9', FALSE),
('Duke', 'Mitchell', 21, '23', FALSE),
('Mbappé', 'Kylian', 22, '61', FALSE),
('Mbappé', 'Kylian', 22, '86', FALSE),
('Christensen', 'Andreas', 22, '68', FALSE),
('Leckie', 'Mathew', 23, '60', FALSE),
('Khazri', 'Wahbi', 24, '58', FALSE),

-- GroupE
('Gündogan', 'Ilkay', 25, '33', FALSE),
('Doan', 'Ritsu', 25, '75', FALSE),
('Asano', 'Takuma', 25, '83', FALSE),
('Olmo', 'Dani', 26, '11', FALSE),
('Asensio', 'Marco', 26, '21', FALSE),
('Torres Garcia', 'Ferran', 26, '31', FALSE),
('Torres Garcia', 'Ferran', 26, '54', FALSE),
('Gavira', 'Pablo', 26, '74', FALSE),
('Soler', 'Carlos', 26, '90', FALSE),
('Morata', 'Alvaro', 26, '90+2', FALSE),
('Fuller', 'Keysher', 27, '81', FALSE),
('Morata', 'Alvaro', 28, '62', FALSE),
('Fullkrug', 'Niclas', 28, '83', FALSE),
('Doan', 'Ritsu', 29, '48', FALSE),
('Tanaka', 'Ao', 29, '51', FALSE),
('Morata', 'Alvaro', 29, '11', FALSE),
('Tejeda', 'Yeltsin', 30, '58', FALSE),
('Neuer', 'Manuel', 30, '70', FALSE),
('Gnabry', 'Serge', 30, '10', FALSE),
('Havertz', 'Kai', 30, '73', FALSE),
('Havertz', 'Kai', 30, '85', FALSE),
('Fullkrug', 'Niclas', 30, '89', FALSE),

-- GroupF
('Batshuayi', 'Michy', 32, '44', FALSE),
('Sabiri', 'Abdelhamid', 33, '73', FALSE),
('Aboukhlal', 'Zakaria', 33, '90+2', FALSE),
('Kramaric', 'Andrej', 34, '36', FALSE),
('Kramaric', 'Andrej', 34, '70', FALSE),
('Livaja', 'Marko', 34, '44', FALSE),
('Majer', 'Lovro', 34, '90+4', FALSE),
('Davies', 'Alphonso', 34, '2', FALSE),
('Aguerd', 'Nayef', 36, '40', FALSE),
('Ziyech', 'Hakim', 36, '4', FALSE),
('En-Nesyri', 'Youssef', 36, '23', FALSE),

-- GroupG
('Embolo', 'Breel', 37, '48', FALSE),
('de Andrade', 'Richarlison', 38, '62', FALSE),
('de Andrade', 'Richarlison', 38, '73', FALSE),
('Castelletto', 'Jean-Charles', 39, '29', FALSE),
('Aboubakar', 'Vincent', 39, '63', FALSE),
('Choupo-Moting', 'Eric Maxim', 39, '66', FALSE),
('Pavlovic', 'Strahinja', 39, '45+1', FALSE),
('Milinković-Savić', 'Sergej', 39, '45+3', FALSE),
('Mitrovic', 'Aleksandar', 39, '53', FALSE),
('Casemiro', 'Carlos', 40, '83', FALSE),
('Mitrovic', 'Aleksandar', 41, '26', FALSE),
('Vlahović', 'Dušan', 41, '35', FALSE),
('Shaqiri', 'Xherdan', 41, '20', FALSE),
('Embolo', 'Breel', 41, '44', FALSE),
('Freuler', 'Remo', 41, '48', FALSE),
('Aboubakar', 'Vincent', 42, '90+2', FALSE),

-- GroupH
('Ronaldo', 'Cristiano', 44, '65', FALSE),
('Felix', 'Joao', 44, '78', FALSE),
('Leao', 'Rafael', 44, '80', FALSE),
('Ayew', 'Andre', 44, '73', FALSE),
('Bukari', 'Osman', 44, '89', FALSE),
('Cho', 'Gue-sung', 45, '58', FALSE),
('Cho', 'Gue-sung', 45, '61', FALSE),
('Salisu', 'Mohammed', 45, '24', FALSE),
('Kudus', 'Mohammed', 45, '34', FALSE),
('Kudus', 'Mohammed', 45, '68', FALSE),
('Fernandes', 'Bruno', 46, '54', FALSE),
('Fernandes', 'Bruno', 46, '90+3', FALSE),
('De Arrascaeta', 'Giorgian', 47, '26', FALSE),
('De Arrascaeta', 'Giorgian', 47, '32', FALSE),
('Kim', 'Young-gwon', 48, '27', FALSE),
('Hwang', 'Hee-chan', 48, '90+1', FALSE),
('Horta', 'Ricardo', 48, '5', FALSE),

-- Round16
('Depay', 'Memphis', 49, '10', FALSE),
('Blind', 'Daley', 49, '45+1', FALSE),
('Dumfries', 'Denzel', 49, '81', FALSE),
('Wright', 'Haji', 49, '76', FALSE),
('Messi', 'Lionel', 50, '35', FALSE),
('Alvarez', 'Julian', 50, '57', FALSE),
('Fernandez', 'Enzo', 50, '77', FALSE),
('Giroud', 'Olivier', 51, '44', FALSE),
('Mbappé', 'Kylian', 51, '74', FALSE),
('Mbappé', 'Kylian', 51, '90+1', FALSE),
('Lewandowski', 'Robert', 51, '90+9', FALSE),
('Henderson', 'Jordan', 52, '38', FALSE),
('Kane', 'Harry', 52, '45+3', FALSE),
('Saka', 'Bukayo', 52, '57', FALSE),
('Maeda', 'Daizen', 53, '43', FALSE),
('Perisic', 'Ivan', 53, '55', FALSE),
('Junior', 'Vinícius', 54, '7', FALSE),
('da Silva Santos Junior', 'Neymar', 54, '13', FALSE),
('de Andrade', 'Richarlison', 54, '29', FALSE),
('Paquetá', 'Lucas', 54, '36', FALSE),
('Paik', 'Seung-ho', 54, '76', FALSE),
('Ramos', 'Goncalo', 56, '17', FALSE),
('Ramos', 'Goncalo', 56, '51', FALSE),
('Ramos', 'Goncalo', 56, '67', FALSE),
('Ferreira', 'Képler', 56, '33', FALSE),
('Guerreiro', 'Raphaël', 56, '55', FALSE),
('Leao', 'Rafael', 56, '90+2', FALSE),
('Akanji', 'Manuel', 56, '58', FALSE),

-- Quarter final
('Petkovic', 'Bruno', 57, '116', FALSE),
('da Silva Santos Junior', 'Neymar', 57, '105+1', FALSE),
('Weghorst', 'Wout', 58, '83', FALSE),
('Weghorst', 'Wout', 58, '90+11', FALSE),
('Molina', 'Nahuel', 58, '35', FALSE),
('Messi', 'Lionel', 58, '73', FALSE),
('En-Nesyri', 'Youssef', 59, '42', FALSE),
('Kane', 'Harry', 60, '54', FALSE),
('Tchouaméni', 'Aurélien', 60, '17', FALSE),
('Giroud', 'Olivier', 60, '78', FALSE),

-- Semi final
('Messi', 'Lionel', 61, '34', FALSE),
('Alvarez', 'Julian', 61, '39', FALSE),
('Alvarez', 'Julian', 61, '69', FALSE),
('Hernandez', 'Theo', 62, '5', FALSE),
('Muani', 'Randal Kolo', 62, '79', FALSE),

-- Third place
('Gvardiol', 'Josko', 63, '7', FALSE),
('Orsic', 'Mislav', 63, '42', FALSE),
('Dari', 'Achraf', 63, '9', FALSE),

-- Final
('Messi', 'Lionel', 64, '23', FALSE),
('Messi', 'Lionel', 64, '108', FALSE),
('Maria', 'Angel Di', 64, '36', FALSE),
('Mbappé', 'Kylian', 64, '80', FALSE),
('Mbappé', 'Kylian', 64, '81', FALSE),
('Mbappé', 'Kylian', 64, '118', FALSE);

-- =========================================================
-- Insert Goals (Penalty Shootout only) ※ is_penalty_shootout = TRUE
-- =========================================================
INSERT INTO Goal (player_lastname, player_surname, match_id, goalTime, is_penalty_shootout) VALUES
-- Round16 Match ID: 53
('Asano', 'Takuma', 53, 'PK', TRUE),
('Vlasic', 'Nikola', 53, 'PK', TRUE),
('Brozovic', 'Marcelo', 53, 'PK', TRUE),
('Pasalic', 'Mario', 53, 'PK', TRUE),

-- Round16 Match ID: 55
('Sabiri', 'Abdelhamid', 55, 'PK', TRUE),
('Ziyech', 'Hakim', 55, 'PK', TRUE),
('Hakimi', 'Achraf', 55, 'PK', TRUE),

-- Quarter final Match ID: 57
('Casemiro', 'Carlos', 57, 'PK', TRUE),
('Guilherme', 'Pedro', 57, 'PK', TRUE),
('Vlasic', 'Nikola', 57, 'PK', TRUE),
('Brozovic', 'Marcelo', 57, 'PK', TRUE),
('Modric', 'Luka', 57, 'PK', TRUE),
('Orsic', 'Mislav', 57, 'PK', TRUE),

-- Quarter final Match ID: 58
('Koopmeiners', 'Teun', 58, 'PK', TRUE),
('Weghorst', 'Wout', 58, 'PK', TRUE),
('de Jong', 'Luuk', 58, 'PK', TRUE),
('Messi', 'Lionel', 58, 'PK', TRUE),
('Paredes', 'Leandro', 58, 'PK', TRUE),
('Montiel', 'Gonzalo', 58, 'PK', TRUE),
('Martinez', 'Lautaro', 58, 'PK', TRUE),

-- Final Match ID: 64
('Mbappé', 'Kylian', 64, 'PK', TRUE),
('Muani', 'Randal Kolo', 64, 'PK', TRUE),
('Messi', 'Lionel', 64, 'PK', TRUE),
('Dybala', 'Paulo', 64, 'PK', TRUE),
('Paredes', 'Leandro', 64, 'PK', TRUE),
('Montiel', 'Gonzalo', 64, 'PK', TRUE);
